### PR TITLE
Use global YAML configuration file

### LINKED ISSUE #11: Move configuration to global location
Currently the `ood-portal-generator` configuration exists under the installation path for `ood-portal-generator`. This typically is in the home directory of the person who installed Open OnDemand.

This causes the configuration file to be easily lost or the sys admins forget about it and directly edit the Apache config.

A simple solution is to:

- read the `ood-portal-generator` YAML configuration file from a well-defined global location such as `/etc/ood/config/ood-portal.yml`
- leave verbose documentation in the Apache config about not directly editing the Apache config but instead to use the global `ood-portal-generator` configuration file

### PR DESCRIPTION
**Pull request by nickjer**
Fixes #11

### CODE REVIEW

**Comment by nickjer** [comment]
Need to deploy it to webdev05/07.

**Comment by nickjer** [comment]
Currently the Puppet module uses the ERB template `templates/ood-portal.conf.erb` to generate the Apache config (These are kept in sync). This update breaks away from that and uses a global YAML configuration file followed by a call to `bin/generate` to generate the Apache config file.

I can continue to make it backwards compatible by hardcoding the ood-portal-generator version in the ERB template. But I feel Puppet can be modified to generate the global YAML configuration file instead (similar to what it does for the cluster configs). Then sub-sequentially call the `bin/generate ...` to generate the Apache config when the YAML config is updated (similar to the `nginx_stage` calls after the cluster configs change to restart the PUNs).

**Comment by nickjer** [comment]
Deployed it to webdev07 using:

```sh
# /etc/ood/config/ood_portal.yml
---
servername: webdev07.hpc.osc.edu
ssl:
  - 'SSLCertificateFile "/etc/pki/tls/certs/webdev07.hpc.osc.edu.crt"'
  - 'SSLCertificateKeyFile "/etc/pki/tls/private/webdev07.hpc.osc.edu.key"'
  - 'SSLCertificateChainFile "/etc/pki/tls/certs/webdev07.hpc.osc.edu-interm.crt"'
auth:
  - 'AuthType Basic'
  - 'AuthName "private"'
  - 'AuthBasicProvider ldap'
  - 'AuthLDAPURL "ldaps://openldap1.infra.osc.edu:636/ou=People,ou=hpc,o=osc?uid" SSL'
  - 'AuthLDAPGroupAttribute memberUid'
  - 'AuthLDAPGroupAttributeIsDN off'
  - 'RequestHeader unset Authorization'
  - 'Require valid-user'
```

and a global installation of the `ood-portal-generator` at:

```
/opt/ood/ood-portal-generator
```

I can then change the global config and run:

```console
$ sudo /opt/ood/ood-portal-generator/bin/generate -o /opt/rh/httpd24/root/etc/httpd/conf.d/ood-portal.conf
```

Followed by an Apache restart to have changes take effect:

```console
$ sudo systemctl restart httpd24-httpd
```

**Comment by ericfranz** [comment]
Why the rewrite and coupling the rewrite with the shift to a global config?

**Comment by nickjer** [comment]
The Rakefile is too constraining as a CLI and would make refreshing the Apache config from a global YAML configuration file difficult.

The change to a full-on CLI came about when I was experimenting with a real-world application of the global configuration file here:

https://github.com/OSC/ondemand/tree/add-rpm-support

Basically I just moved the Ruby class from the Rakefile to a Ruby library file. The Rakefile still behaves identically as it did before.

**Review by ericfranz — CHANGES_REQUESTED** [review]
Local config required!

https://osc.github.io/ood-documentation/master/updating/update-apache-config.html

**Pull request merged**
